[package]
edition = "2021"
name = "asena"
version = "0.1.0"

[build-dependencies]
lalrpop = "0.19.7"

[dependencies]
fxhash = "0.2.1"
im = "15.1.0"
lalrpop-util = {version = "0.19.7", features = ["lexer"]}
substring = "1.4.5"
